name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-71.0.dev

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.5.4
  cryptography: ^2.7.0
  dart_wot: ^0.27.1
  pointycastle: ^3.7.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
