name: cli
description: A sample command-line application.
version: 1.0.0
publish_to: none

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-71.0.dev

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.5.4
  cbor: ^5.1.2
  cryptography: ^2.7.0
  dart_wot: ^0.27.1
  fixnum: ^1.1.0
  # grpc:
    # path: /home/parallels/go/src/github.com/grpc/grpc-dart
  grpc: ^3.2.4
  pointycastle: ^3.7.3
  authn:
    path: packages/authn
#    path: /home/parallels/go/src/github.com/lainio/dart_cli/packages/authn


  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  protobuf: ^3.0.0
